//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPCI.Modules.DNN_Clones_Module_Manager_DevPCI_Clonator
{


    public partial class Edit
    {
    }
}
